[package]
name = "rust_crud"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.1.1"
dotenv = "0.15"
futures = "0.3.31"
axum = "0.8.1"
bson = { version = "2", features = ["chrono-0_4"] }
tokio = "1"
chrono = "0.4"
serde = "1"
